import Head from "next/head";
import Container from "@/components/Container";
import Carousel from "@/components/Carousel";
import { useAppDispatch, useAppSelector } from "@/redux/hooks";
import { useEffect } from "react";
import { fetchProducts, selectProducts } from "@/redux/slices/product-slice";
import { Flex, Spinner } from "@chakra-ui/react";

export default function Home() {
  const dispatch = useAppDispatch();
  const { loading } = useAppSelector(selectProducts);

  useEffect(() => {
    dispatch(fetchProducts());
  }, [dispatch]);

  return (
    <>
      <Head>
        <title>Ecommerce App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {loading ? (
          <Flex
            minW="100vw"
            minH="100vh"
            alignItems="center"
            justifyContent="center"
          >
            <Spinner color="brand.500" size="xl" />
          </Flex>
        ) : (
          <>
            <Container />
            <Carousel />
          </>
        )}
      </main>
    </>
  );
}
